#+title: Aboriginal Art Symbols in Dot Painting: Larapinta Dreaming
#+date: 2019-04-05
#+categories[]: Culture
#+tags[]: Art Indigenous
#+images[]: /images/larapinta/larapinta-dreaming-banner.jpg
#+description: 

The ancestors of today's Aboriginal people populated the Australian continent about tens of thousands of years ago. Their culture is in many respects unique because, until the eighteenth century, they had limited contact with people outside Australia. One of the most striking manifestations of contemporary Aboriginal culture are the iconic dot paintings of the desert people. Dot paintings include many Aboriginal art symbols that convey meaning to the work. This article discusses the hidden meaning of Aboriginal art by analysing /Larapinta Dreaming/ by Marylin Armstrong.

Before colonial times, Aboriginal culture was fully embedded in its natural environment. Aboriginal material culture revolved around practical and ritual objects. Craftsmen and women adorned spears, baskets, shields, ritual and ceremonial poles with culturally meaningful patterns. Aboriginals expressed their art with natural materials such as rocks, sand, wood, bark, beeswax, reeds and occasionally bodily fluids. 

The people of the Australian deserts traditionally expressed their art with sand drawings, painting their bodies, and the more enduring rock paintings and engravings.[fn:1]

#+CAPTION: Yugambeh Aboriginal man in Queensland with body painting.
file:static/images/larapinta/Yugambeh-Aboriginal-warrior.jpg
* The Dreamtime
The /Dreamtime/ is the defining aspect of traditional Aboriginal culture. This is a primordial period which is the source of all social, legal, practical and metaphysical knowledge. This time is retold through rituals and mythology. These rituals and stories contain the sum total of all traditional knowledge that is handed down for generations. Sons learn these stories from their fathers and daughters learn them from their mothers. Each Dreaming is owned by an individual or by a clan group. Most accounts of the Dreamtime are strictly confidential and known only to the initiates of the relevant Dreaming. 

The stories of the Dreamtime feature mythical creatures that once travelled the land and created its current features. The stories of the On the surface, Dreamtime seem like a silly bedtime story for children. These myths do, however, contain a wealth of practical and cultural knowledge. A legend about an ancestral creature having a drink a particular location is an indication that this is a place to find water. Stories about relationships between Dreamtime ancestors might contain a lesson about human relationships. The Dreamtime was an essential storehouse of knowledge for a culture without writing.
* The Dreamtime as a Knowledge Store
The owner of the Dreaming maintains the landscape associated with these stories. They are not owners of the land in the Western legal sense but custodians on behalf of the Dreamtime ancestors. They manage the land using traditional methods, such as fire-stick farming. The idea that Aboriginals were passive nomads is wrong because they took care of the land to ensure that food and water would be available. The Dreamtime stories provided Aboriginal people with traditional knowledge to manage their land and society.[fn:2]

These stories have a multi-layered logic. The seemingly simple stories at the surface hide profound practical and cultural knowledge. The logic of the stories or songs is a mnemonic device to help people remember large amounts of text.[fn:3] One of the methods to transfer this knowledge was through works of art. Traditional works of Aboriginal art are imbued with meaning. Aboriginal art symbols are used as a proto-language to communicate the Dreamings.

#+CAPTION: MacDonnell Ranges, showing two caterpillars in the landscape.
file:static/images/larapinta/mcdonnel-ranges.jpg
* Aboriginal Art Symbols
The characteristic patterns of central desert Aboriginal art, such as the iconic dots and concentric circles, are a symbolic language that illustrates stories of the Dreamtime. Dot paintings are not the traditional domain of all Aboriginals peoples. The art of Arnhem Land, for example, is more figurative with semi-realistic people and animals. Each Aboriginal nation or tribe developed their own distinct visual language.

The experience of Aboriginal art is different from the Western understanding. The most significant difference is that traditional art is entirely practical. The art used to be exclusively manufactured to share or enact the stories of the Dreamtime. Traditional art is in this sense thus a form of communication and medium for transferring knowledge. 

Body painting in rituals depicts events from the Dreamtime. Sand Mosaics are not just viewed, but experienced by ritually singing and dancing through them, destroying the works in the process. The contemporary painters of central Australia derive their works from these traditional sound drawings and body paintings.

Most Aboriginal artists produce their paintings horizontally on the ground by sitting around the canvas. This method is in contrast with Western art traditions which are created vertically on an easel. Jackson Pollock is a famous example of an American painter who also places his canvases on the ground to paint. Museums display the works of Aboriginal artists almost always vertically, following the conventions of Western art. One exception is the Art Gallery of South Australia. They exhibit a monumental work of Clifford Possum horizontally.

#+CAPTION: Clifford Possum Tjapaltjarri, Anmatyerr people (1932 – 2002). /Possum Dreaming/ 1994 (National Gallery of Australia).
file:static/images/larapinta/possum-dreaming.jpg
* Contemporary Dot Painting
Aboriginal art as we currently know it is fairly new and only became appreciated by a wider audience in the nineteen seventies. Geoffrey Bardon, who taught at [[http://www.papunyatula.com.au/][Papunya Tula]], brought this art to the attention of the Western world. Papunya Tula is one of many settlements for aboriginal people, established by the Australian government in the middle of the last century. Officials forcefully removed people from their traditional land and taken to these settlements. This displacement caused immense stress because the government separated indigenous people from their traditional way of life. 

After Bardon observed the importance of drawings in their culture, he provided the men in Papunya Tula materials to express their traditional art. As a result, the men painted a mural on a blank wall, which started of the now world-renowned central and western desert art.

Modern materials, such as acrylic paint, have opened a new world for Aboriginal artists. The traditional designs influence modern works, but they have lost their ritual purpose. This distinction also becomes clear in the exhibition spaces. Art galleries display contemporary works. Anthropological museums exhibit objects such as baskets and boomerangs. The inspiration for both is, however, the same: the stories of the Dreamtime.

The designs of Aboriginal art from the Australian desert are almost entirely abstract, and each painting has several layers of meaning. The meaning of Aboriginal art is therefore not apparent from simply analysing the patterns on the canvas. The true meaning of the work lies outside of the picture itself. The deeper meaning of Aboriginal art subsequently transcends the painting as a physical object. The meaning of all art, including the indigenous kind, exists on four different levels.
** First level of meaning
The first level of meaning relates to the physical appearance of the work of art. Its materials, composition, colours and so on.

On the first level, the famous dots in both foreground and background dominate paintings of the Australian desert tradition. The paintings generally do not include any figurative elements, but a culturally specific symbolic language of concentric circles, animal tracks and other shapes. 

The paintings from the early modern period are almost entirely abstract and are close to the traditional sand drawings from which they originate. Nature limits the traditional colour range to what is available in the environment. The contemporary art of central Australia is, however, detached from these limitations and uses more colours and symbolic elements.[fn:4]

#+CAPTION: Aboriginal art symbols.
file:static/images/larapinta/aboriginal-art-symbols.jpg
** Second level of meaning
The second level of meaning relates to the physical reality that the work of art expresses. The dot paintings depict the natural landscape that is connected with stories from the Dreamtime. The activities of the Dreamtime ancestors shaped the land which resulted in the current geological structures. 

Traditional sand paintings contained practical and cultural knowledge about the landscape and the tribe. On a practical level, these works of art communicated the places where water and food could be found. The cultural level contains knowledge about kinship and other social aspects of life.

As drawing in the sand has limitations, a rich symbolic language expresses the stories of the Dreamtime.[fn:5] This proto-language transferred practical and cultural knowledge between generations for thousands of years.
** Third level of meaning
At the third level, the designs represent the ceremonies which re-enact the epic journeys of the Dreamtime ancestors. Members of the clan perform these ceremonies as part of a cultural calendar throughout the year. 

At this level, the paintings are multi-dimensional and express a series of events in time in one image. Other than a figurative image which usually shows a moment in time, Aboriginal art can express a series of events.
** Fourth level of meaning
On the fourth and most profound level, the pictures contain spiritual knowledge that is known only to insiders of the Dreaming. Not much is therefore publicly known about this deepest level of interpretation since this knowledge secret. 

In traditional Aboriginal culture, the sacred and the secret almost fully overlap. This sense of secrecy can create tension with the unlimited curiosity characteristic of Western culture. It is not only forbidden to share knowledge with outsiders, even within the tribes there are strict rules on the distribution of knowledge. 

The emphasis on secrecy in Aboriginal culture can thus cause cultural tensions in the contemporary world. The website of the Art Gallery of South Australia used to warn about the esoteric content of the displayed works: 

#+begin_quote
… this site may include images of a culturally sensitive nature. All efforts have been made to ensure that restricted works are not included.
#+end_quote

The exhibition of works that depict secret stories has been problematic in the past. The drive of art enthusiasts to know the hidden meaning of paintings has caused artists to develop more complex and busy designs to obfuscate the deeper meaning of the paintings. Aboriginal Artist [[https://www.artgallery.nsw.gov.au/collection/artists/tjapaltjarri-tim-leura/][Tim Leura]] considers the patterns he paints on canvas to be mere toys. The serious work is painted on the bodies of people or the ground when undertaking a ceremony.
* Larapinta Dreaming
I purchased /Larapinta Dreaming/ in 2003 from one of the many galleries that are dotted around Alice Springs. Aboriginal art is popular among tourists, and a vital source of income for many Aborigines.

/Larapinta Dreaming/ is painted in acrylic on canvas (63 x 41 cm) by Marilyn Armstrong from Hermansburg near Alice Springs. Marilyn was born in Jay Creek community, in the red heart of Australia. As a child she came into contact with famous Aboriginal painters such as Albert Namatjira and Clifford Possum and in 1986 she started to paint Dreamtime stories herself.

#+CAPTION: Marylin Armstrong (2003?), Larapinta Dreaming. Acrylic on canvas (63 x cm).
file:static/images/larapinta/larapinta-dreaming.jpg
** First and second level
The most striking element of Larapinta Dreaming is the oval ring of caterpillars, the 'larapinta', encircling a collection of emu and dingo tracks. The background of the painting is entirely made of dots in varying colours, except for the central part of the composition. The colour palette of this work contains many bright colours, a recent development in contemporary Aboriginal art. The back of the painting reveals the second level of meaning:

#+begin_quote
This area got many sacred sites, and there is one where the dogs vomit. Other side is where the women had been meetings, dances and also the caterpillar dreamings where the Aranda people camp is.

Marilyn Armstrong, Mbilja Nampitjinpa.
#+end_quote

#+CAPTION: Narrative elements of Larapinta Dreaming.
file:static/images/larapinta/larapinta-dreaming-design.jpg

On the second level of meaning, this painting refers to the MacDonnell Ranges, the geological formations around Alice Springs that look like caterpillars, shown in the photograph above. This painting is thus probably a reference to an unnamed ceremonial place in the MacDonnell Ranges.
** Deeper levels
Since I am not initiated into the deeper meaning of the /Larapinta Dreaming/, I cannot comment on its ceremonial and metaphysical significance, which constitutes the third and fourth level of meaning. 

I could speculate that since a woman painted this canvas, the vomiting might be related to morning sickness of pregnant women and that this painting refers to a place where pregnant women gather and share knowledge with the elders. However, this is pure speculation on my part.
* Footnotes
[fn:1] Ronald M. Berndt and Catherine H. Berndt, /The world of the first Australians. Australian traditional life: Past and present/ (Fifth edition, Canberra 1996).
[fn:2] Bardon, Geoffrey, /Papunya Tula. Art of the western desert/ (Marlston 1999), pp. 2-3.
[fn:3] Lynne Kelly (2016). /The Memory Code/. Allen & Unwin.
[fn:4] Stokes, Deidre, /Desert Dreamings/ (Port Melbourne 1993).
[fn:5] James Cowan. /Aborigine dreaming/ (London 1992).
