# Third Hemisphere Hugo Theme

This is a work-in-progress to create an SEO-optimised HUGO theme. Principles:
- Optimised technical SEO, including [[https://schema.org/][schema.org]] for articles
- Mimicking the functionality of the [[https://yoast.com/][Yoast SEO Wordpress]] plugin
- Uses [[https://bulma.io/][Bulma CSS]], based on the work by [[https://www.pakstech.com/blog/create-hugo-theme/][Päktech]]

This theme is in development and is not available in the wild just yet.

* Technical SEO
This theme implements the following
- Meta tags for title, description, canonical and hreflang self-referencing links.
- Robots meta tags configurable with the `seo` page variable.
  - `true`: index, follow
  - `false` or missing: noindex, nofollow

The head of the html file contains the usual meta tags. 
** SEO Assessment
This theme also contains a partial that assess the content of each single page. This module implements some of the features of the popular Wordpress Yoast plugin. The check is based on the =keyphrase= page parameter. This is the series of words that visitors to your page will most likely use in their search engine. This keyphrase needs to appear at strategic positions in your page.

The SEO module check for the following characteristics:
- [[https://yoa.st/34h][Title width]] between 50 and 60 characters.
- [[https://yoa.st/34d][Meta description]] between 120 and 156 characters.
- [[https://yoa.st/33c][Featured image]] is present (the template will assign the meta description to the alt tag).
- [[https://yoa.st/34n][Content length]] is at least 300 words.
- [[https://yoa.st/34i][Keyphrase]] between 1 and 4 words.
- [[appearse in][Keyphrase]] appears in the title.
- [[https://yoa.st/33k][Keyphrase]] appears in meta description.
- [[https://yoa.st/33e][Keyphrase]] appears in first paragraph (first 7 words).
- [[https://yoa.st/33m][Keyphrase]] appears in headings.
- [[https://yoa.st/33o][Keyphrase]] appears in slug
- [[https://yoa.st/33x][Keyphrase]] is not duplicated in another page.

Each page has a default =seo= parameter that is set to =true= by default. If the parameter is set to =false=, then the [[https://developers.google.com/search/reference/robots_meta_tag][robots meta tag]] is set to "noindex, nofollow". Resetting this parameter will also remove the SEO check.
** Structured data
Each single page has an article [[https://developers.google.com/search/docs/guides/intro-structured-data][structured data schema]] with meta data for search engines and social media.
** Canonical content
All taxonomy pages are enabled with content to develop canonical content. As pages are tagged with their category or tag, a network of links is created that 
* Social Media links
The social media menu in the =config.toml= provides icons and links to your profiles. You can find the icons on the [[https://fontawesome.com/icons?d=gallery][Font Awesome]] website, e.g. "=fab fa-github=". The icons link to the [[https://cdn.fontawesome.com/][Font Awesome CDN]]. You will need to get your own CDN-link and add it to the config file to make it work.
* Copyright statement
A copyright statement appears in the central footer column with the appropriate icon. The `license` variable in the site parameters section of your configuration file holds the copyright statement text. the `cc` variable holds the icon name from the [[https://fontawesome.com/][Font Awesome]] library.
* Branding
The logo image is a square png file that is used in the navigation bar and as the favicon. The location of the logo file is identified in the params section of the config file, e.g. =logo = "/favicon.png"=.

Ideally, a website has several versions of icons for the various browsers on desktop and mobile. The [[https://realfavicongenerator.net/][Favicon Generator]] website helps you to create a complete set. This theme only uses a 128 by 128 pixel png file, which most browsers seem to be able to handle.
* Contact form
The =contact-from= shortcode enables the form by assigning an endpoint that processes the data. The example below uses [[https://formspree.io/][Formspree]], that can be any other endpoint.
#+begin_src 
{{< contact-form endpoint="https://formspree.io/jtshwodj" >}}
#+end_src

* External links
The =lnk= shortcode helps to create blank targets for external links. ={{< lnk url="https://website.com/" >}}=
